title: "Knowledge Base"
description: "A simple knowledge base created with Jekyll."
baseurl: "/site"
url: "https://manishkamarapu.github.io" # replace <username> with your GitHub username
theme: minima
